import React from 'react'

const TermsConditions = () => {

    return (
    
        <div className="md:flex space-x-16 mt-5 md:mr-0 mr-10 pl-2 pr-2 md:pl-10 md:pr-10 xl:pl-80 xl:pr-80">
        <div className="md:flex items-center">
          <div className="">
            <h1 className="text-5xl text-textColor font-medium leading-snug tracking-wider">{"TERMS & CONDITIONS"}</h1>
            <p className="text-mainColor mt-4 text-lg font-normal">Dimension Doors is a collection of digital artworks (NFTs) running on the Ethereum network. This website is only an interface allowing participants to exchange digital collectibles. Users are entirely responsible for the safety and management of their own private Ethereum wallets and validating all transactions and contracts generated by this website before approval. Furthermore, as the Dimension Doors smart contract runs on the Ethereum network, there is no ability to undo, reverse, or restore any transactions.

            This website and its connected services are provided “as is” and “as available” without warranty of any kind. By using this website you are accepting sole responsibility for any and all transactions involving Dimension Doors digital collectibles. 
            </p><br></br>

            <h1 className="text-4xl text-textColor font-medium leading-snug tracking-wider">OWNERSHIP</h1>
            <p className="text-mainColor mt-4 text-lg font-normal">i. You Own the NFT. Each Dimension Door is an NFT on the Ethereum blockchain. When you purchase an NFT, you own the underlying Dimension Door, the Art, completely. Ownership of the NFT is mediated entirely by the Smart Contract and the Ethereum Network: at no point may I seize, freeze, or otherwise modify the ownership of any Dimension Door.

ii. Personal Use. Subject to your continued compliance with these Terms, Moot grants you a worldwide, royalty-free license to use, copy, and display the purchased Art, along with any extensions that you choose to create or use, solely forthe following purposes: (i) for your own personal, non-commercial use; (ii) as part of a marketplace that permits the purchase and sale of your Dimension Door / NFT, provided that the marketplace cryptographically verifies each Dimension Door owner’s rights to display the Art for their Dimension Door to ensure that only the actual owner can display the Art; or (iii) as part of a third party website or application that permits the inclusion, involvement, or participation of your Dimension Door, provided that the website/application cryptographically verifies each Dimension Door owner’s rights to display the Art for their Dimension Door to ensure that only the actual owner can display the Art, and provided that the Art is no longer visible once the owner ofthe Dimension Door leaves the website/application.

iii. Commercial Use. Subject to your continued compliance with these Terms, Moot grants you an unlimited, worldwide license to use, copy, and display the purchased Art for the purpose of creating derivative works based upon the Art (“Commercial Use”). Examples of such Commercial Use would e.g. be the use of the Art to produce and sell merchandise products (T-Shirts etc.) displaying copies of the Art. For the sake of clarity, nothing in this Section will be deemed to restrict you from (i) owning or operating a marketplace that permits the use and sale of Dimension Doors generally, provided that the marketplace cryptographically verifies eachDimension Door owner’s rights to display the Art for their Dimension Door to ensure that only the actual owner can display the Art; (ii) owning or operating a third party website or application that permits the inclusion, involvement, or participation of Dimension Doors generally, provided that the third party website or application cryptographically verifies each Dimension Door owner’s rights to display the Art for theirDimension Door to ensure that only the actual owner can display the Art, and provided that the Art is no longer visible once the owner of the Purchased Dimension Door leaves the website/application; or (iii) earning revenue from any of the foregoing.
            </p><br></br>
              
          </div>
        </div>
      </div>

    )
}

export default TermsConditions
